version: '1'

services:
  licensingservice:
    container_name: licensing-service
    build:
      dockerfile: Dockerfile
    image: ostock/licensing-service:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    networks:
      - backend

networks:
  backend:
    driver: bridge